### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by sengupta** [kennethreitz/tablib#187] opened 2015-03-10 06:37 UTC
There are a bunch of errors that show up while installing tablib using pip. Here's a log. I'm using Python 2.7.6. 

```
$ pip install tablib 
Downloading/unpacking tablib
  Downloading tablib-0.10.0-py2.py3-none-any.whl (864kB): 864kB downloaded
Installing collected packages: tablib
Compiling {path}/venv/build/tablib/tablib/packages/xlrd3/__init__.py ...
  File "{path}/venv/build/tablib/tablib/packages/xlrd3/__init__.py", line 855
    print("mem: %s, base: %d, len: %d" % (type(self.mem), self.base, self.stream_len), file=self.logfile)
                                                                                           ^
SyntaxError: invalid syntax

Compiling {path}/venv/build/tablib/tablib/packages/xlrd3/biffh.py ...
  File "{path}/venv/build/tablib/tablib/packages/xlrd3/biffh.py", line 386
    print(header, file=f)
                      ^
SyntaxError: invalid syntax

Compiling {path}/venv/build/tablib/tablib/packages/xlrd3/compdoc.py ...
  File "{path}/venv/build/tablib/tablib/packages/xlrd3/compdoc.py", line 89
    print("\nCompDoc format: version=0x%04x revision=0x%04x" % (version, revision), file=logfile)
                                                                                        ^
SyntaxError: invalid syntax

Compiling {path}/venv/build/tablib/tablib/packages/xlrd3/formatting.py ...
  File "{path}/venv/build/tablib/tablib/packages/xlrd3/formatting.py", line 589
    print("%2d: %r -> %r" % (i, old_rgb, new_rgb), file=book.logfile)
                                                       ^
SyntaxError: invalid syntax

Compiling {path}/venv/build/tablib/tablib/packages/xlrd3/formula.py ...
  File "{path}/venv/build/tablib/tablib/packages/xlrd3/formula.py", line 794
    if verbose: print("tIsect pre", stack, file=bk.logfile)
                                               ^
SyntaxError: invalid syntax

Compiling {path}/venv/build/tablib/tablib/packages/xlrd3/sheet.py ...
  File "{path}/venv/build/tablib/tablib/packages/xlrd3/sheet.py", line 466
    print("put_cell", rowx, colx, file=self.logfile)
                                      ^
SyntaxError: invalid syntax

Compiling {path}/venv/build/tablib/tablib/packages/xlwt3/antlr.py ...
  File "{path}/venv/build/tablib/tablib/packages/xlwt3/antlr.py", line 1946
    print(fmt % (line,col,text), file=sys.stderr)
                                     ^
SyntaxError: invalid syntax

Successfully installed tablib
Cleaning up...
```

Tablib continues to work after this though.

**Comment by tsroten** [comment] 2015-04-02 10:13
This is actually a duplicate of #177.

**Closed** 2016-02-07 12:32 UTC
