### ISSUE TITLE
Import ascii characters not valid.

### ISSUE THREAD

**Issue by JostCrow** [kennethreitz/tablib#215] opened 2016-02-04 16:42 UTC
I tried to add data to the tablib Dataset. I use django import export to do so. Everything goes well with the data until it is in the dataset. Once it is added and I try to read the data I get the following error. 

```
UnicodeEncodeError encountred while trying to read file: 'ascii' codec can't encode character u'\xc6' in position 241: ordinal not in range(128)
```

It is about the text Ævar. This name will fail when you try to read the data from the Dataset.

**Comment by kennethreitz** [comment] 2016-02-07 12:11
What format were you exporting to?

**Comment by JostCrow** [comment] 2016-02-08 08:58
This is not with an export. I used this to import the data. So when I print the data (via the __unicode__) It will give that error.

**Comment by kennethreitz** [comment] 2016-02-08 21:01
Can you provide the code you used, so we can reproduce?

**Comment by JostCrow** [comment] 2016-02-09 09:11
Yes I will work on this. It will follow later. I can already add the csv file that I used. Maybe that will already help a little?

[dump.csv.zip](https://github.com/kennethreitz/tablib/files/122790/dump.csv.zip)

**Comment by kennethreitz** [comment] 2016-02-09 11:20
Hmmm. This works properly in Python 3.

**Comment by JostCrow** [comment] 2016-02-09 11:21
Does it also work in python 2.7?

**Comment by kennethreitz** [comment] 2016-02-09 11:32
It does not. It should, as we are using the unicodecsv module. Further investigation required.

**Comment by JostCrow** [comment] 2016-02-09 11:34
Ok Thanks.

**Comment by Benny-** [comment] 2017-02-04 17:14
I too have this problem when reading a exported csv file. Observe the following problem:

```python
#!/usr/bin/env python
#-*- coding:utf-8 -*-

import tablib

headers = (u'name', u'foos')

data = [
     (u'ЖЗИЙКЛМНОПР', u'foo1'),
]

dataset = tablib.Dataset(*data, headers=headers)
csv = dataset.csv
encoded_csv = csv.encode('UTF-8') # This line throws exception on python2
```

This above file fails on python2 with the following error:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 11: ordinal not in range(128)

Python3 does not yield any exception.

It is worth to note the type of the final `csv` variable. Is is a class string on python2 and python3:
```python
type(dataset.csv)
# Outputs: <class 'str'>
```

This is wrong. I am putting in unicode and getting strings as output. I guess it is decoding the string to unicode before encoding it to `UTF-8` causing the problem. But this does not really explain why it works on python3, it should not; as a random string can't be converted to any encoding without knowing which encoding the string was in the first place.

Somewhere in the tablib library the Unicode objects are converted to strings.

**Comment by Benny-** [comment] 2017-02-11 01:55
I have done some digging. Here are the result.

`cStringIO` does [not support full unicode set](https://docs.python.org/2/library/stringio.html#module-cStringIO). `cStringIO` is imported [here](https://github.com/kennethreitz/tablib/blob/a93f93a458f6ab3ce48439d2d571e4f88da4c024/tablib/compat.py#L45) as `StringIO` and used in [_csv](https://github.com/kennethreitz/tablib/blob/1d4f4b68ca833a797fc34ff8676f113edf0f64f7/tablib/formats/_csv.py#L6). Proposed solution: Use the real StringIO class (slower but full support for unicode).



python-unicodecsv does not support unicode. No really, the name of this project is a misnomer. Some issues promptly made the author explicitly state that the library [expects a encoded byte stream](https://github.com/jdunck/python-unicodecsv/commit/7241622d7486ca6099f14d6cbca0c7909d0adb99). Here is how unicodecsv works:

```python
#!/usr/bin/env python2
#-*- coding:utf-8 -*-

import unicodecsv
from StringIO import StringIO

# unicodecsv can't handle unicode. Encode the unicode to bytes
# Failure to do this results in encoding errors during the r.next() method
encodedString = u'和製,漢語'.encode('utf-8')
f = StringIO(encodedString)
r = unicodecsv.reader(f, encoding='utf-8')
row = r.next() # Row now contains two valid unicode objects in a list



f = StringIO()
w = unicodecsv.writer(f, encoding='Big5+')
w.writerow((u'和製', u'漢語'))
outputString = f.getvalue()
# outputString contains encoded text. In this case Big5+
# There seems to be no api to get the csv file as unicode
# The only way to get unicode back is to decode the string again.
outputUnicode = outputString.decode('Big5+')
```

Encoding/decoding should happen at the fs/network/io boundary. Not at library boundaries. Proposed solution for python-unicodecsv: Ditch it. [backports.csv](https://pypi.python.org/pypi/backports.csv) looks much saner.

**Comment by Benny-** [comment] 2017-02-21 07:48
I will start working on a patch as soon as I received feedback on the proposed solutions.

**Comment by browniebroke** [comment] 2017-02-22 00:55
I had the same impression and also saw the library backports.csv, but I did not dig enough to get around the encoding considerations. 

Your explanation seems reasonable, and I'm tempted to agree on the impression about backports.csv, but I have to admit it's just a gut feeling.

**Comment by browniebroke** [comment] 2017-02-22 09:03
I've tried to look at your change on my pull request and I realised that tests were behaving quite differently in Python 2 and 3 because of the unicode literals, and I couldn't use `u""` notation on some python 3 versions. 

I've added the future import which resulted in the tests to pass on all Python 3 version, and failing in the same way on Python 2.6 and 2.7.

Then, I've implemented the changes suggested and a couple of others, and they all pass now. I even _had_ to clean up some Python 2 specific code.

**Comment by Benny-** [comment] 2017-02-26 15:58
Great work @browniebroke

**Comment by gthieleb** [comment] 2017-04-24 06:39
Is this already merged into upstream?

**Comment by gthieleb** [comment] 2017-04-27 06:47
Is it possible in the current state of tablib to export a CSV file latin-1 encoded? This is an issue I am struggling for a year now. I need latin-1 encoded CSV because all the guys in my company working with Excel!

**Comment by browniebroke** [comment] 2017-05-02 16:34
Just squashed my commits so it's properly referenced, and rebased master onto my branch.

**Comment by jieter** [comment] 2017-05-29 17:11
@browniebroke @kennethreitz It would be really nice to have this (#270) in a release. How can I help make that happen?

**Closed** 2019-03-02 14:06 UTC
Labels: bug
